name: Check lints and formatting
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - name: Check lints
        run: yarn lint
      - name: Check formatting
        run: yarn prettier --check .
